// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlbqmxQURudeUXhOQB0AtB2EWUcFzX_uY',
    appId: '1:611582097916:web:973c2f41aded2f10a2da79',
    messagingSenderId: '611582097916',
    projectId: 'madhuram-1f7aa',
    authDomain: 'madhuram-1f7aa.firebaseapp.com',
    storageBucket: 'madhuram-1f7aa.firebasestorage.app',
    measurementId: 'G-2LKS963MSZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBum5omsyzT42iWca2f25KYWv8_2BM6SKc',
    appId: '1:611582097916:android:11d28cd9ffe72079a2da79',
    messagingSenderId: '611582097916',
    projectId: 'madhuram-1f7aa',
    storageBucket: 'madhuram-1f7aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCN96ADwnwPdBq6dTj7xbbIRCxKQM_Fk2U',
    appId: '1:611582097916:ios:c9d2627bf9790535a2da79',
    messagingSenderId: '611582097916',
    projectId: 'madhuram-1f7aa',
    storageBucket: 'madhuram-1f7aa.firebasestorage.app',
    iosBundleId: 'com.example.madhuramApp',
  );
}
