export const ACCESS_CONTROL_CATALOG = [
  {
    pagePath: '/',
    pageTitle: 'Dashboard',
    category: 'Main',
    description: 'Project overview, status snapshots, and quick actions.',
    functions: [
      { key: 'dashboard.view', label: 'View Dashboard', description: 'Open dashboard and read summary widgets.' },
      { key: 'dashboard.view_metrics', label: 'View Metrics', description: 'See KPI cards and high-level project metrics.' },
      { key: 'dashboard.quick_actions', label: 'Use Quick Actions', description: 'Access dashboard shortcut actions.' },
    ],
  },
  {
    pagePath: '/projects',
    pageTitle: 'Projects',
    category: 'Project Management',
    description: 'Manage project list and core project details.',
    functions: [
      { key: 'projects.view', label: 'View Projects', description: 'See project list and project information.' },
      { key: 'projects.create', label: 'Create Project', description: 'Create a new project entry.' },
      { key: 'projects.edit', label: 'Edit Project', description: 'Edit existing project details.' },
      { key: 'projects.delete', label: 'Delete Project', description: 'Delete a project record.' },
    ],
  },
  {
    pagePath: '/boq',
    pageTitle: 'BOQ Management',
    category: 'Project Management',
    description: 'Handle bill of quantities and related items.',
    functions: [
      { key: 'boq.view', label: 'View BOQ', description: 'Open and review BOQ data.' },
      { key: 'boq.create', label: 'Create BOQ', description: 'Add new BOQ entries.' },
      { key: 'boq.edit', label: 'Edit BOQ', description: 'Update BOQ entries.' },
      { key: 'boq.approve', label: 'Approve BOQ', description: 'Approve or finalize BOQ items.' },
    ],
  },
  {
    pagePath: '/mas',
    pageTitle: 'MAS',
    category: 'Project Management',
    description: 'Material approval and status workflows.',
    functions: [
      { key: 'mas.view', label: 'View MAS', description: 'Read MAS records and statuses.' },
      { key: 'mas.create', label: 'Create MAS', description: 'Create MAS records.' },
      { key: 'mas.edit', label: 'Edit MAS', description: 'Edit MAS details.' },
      { key: 'mas.approve', label: 'Approve MAS', description: 'Approve MAS workflow items.' },
    ],
  },
  {
    pagePath: '/samples',
    pageTitle: 'Sample Management',
    category: 'Procurement',
    description: 'Track samples from request to approval.',
    functions: [
      { key: 'samples.view', label: 'View Samples', description: 'View sample list and records.' },
      { key: 'samples.create', label: 'Create Sample', description: 'Add a new sample entry.' },
      { key: 'samples.edit', label: 'Edit Sample', description: 'Modify sample details.' },
      { key: 'samples.approve', label: 'Approve Sample', description: 'Approve or reject sample items.' },
    ],
  },
  {
    pagePath: '/purchase-requests',
    pageTitle: 'Purchase Requests',
    category: 'Procurement',
    description: 'Create, edit, and track purchase requisitions.',
    functions: [
      { key: 'purchase_requests.view', label: 'View PRs', description: 'Open purchase request list and details.' },
      { key: 'purchase_requests.create', label: 'Create PR', description: 'Create new purchase requests.' },
      { key: 'purchase_requests.edit', label: 'Edit PR', description: 'Update existing purchase requests.' },
      { key: 'purchase_requests.delete', label: 'Delete PR', description: 'Delete purchase requests.' },
    ],
  },
  {
    pagePath: '/purchase-orders',
    pageTitle: 'Purchase Orders',
    category: 'Procurement',
    description: 'Create, manage, and track purchase orders.',
    functions: [
      { key: 'purchase_orders.view', label: 'View POs', description: 'Open purchase order list and details.' },
      { key: 'purchase_orders.create', label: 'Create PO', description: 'Create new purchase orders.' },
      { key: 'purchase_orders.edit', label: 'Edit PO', description: 'Update purchase order details.' },
      { key: 'purchase_orders.approve', label: 'Approve PO', description: 'Approve or release purchase orders.' },
    ],
  },
  {
    pagePath: '/vendors',
    pageTitle: 'Vendors',
    category: 'Procurement',
    description: 'Maintain vendor records and profiles.',
    functions: [
      { key: 'vendors.view', label: 'View Vendors', description: 'View vendor list and profiles.' },
      { key: 'vendors.create', label: 'Create Vendor', description: 'Add vendor records.' },
      { key: 'vendors.edit', label: 'Edit Vendor', description: 'Update vendor details.' },
      { key: 'vendors.delete', label: 'Delete Vendor', description: 'Remove vendor records.' },
    ],
  },
  {
    pagePath: '/vendor-comparison',
    pageTitle: 'Vendor Comparison',
    category: 'Procurement',
    description: 'Compare vendor price list items and identify the best offers.',
    functions: [
      { key: 'vendor_comparison.view', label: 'View Vendor Comparison', description: 'Open the vendor comparison page.' },
      { key: 'vendor_comparison.search', label: 'Search Comparison Items', description: 'Search and filter vendor comparison results.' },
      { key: 'vendor_comparison.compare', label: 'Compare Vendor Offers', description: 'Run comparisons across vendor price lists.' },
    ],
  },
  {
    pagePath: '/quotes/add',
    pageTitle: 'Quotes',
    category: 'Procurement',
    description: 'Review quotations and create new ones.',
    functions: [
      { key: 'quotes.view', label: 'View Quotes', description: 'Open the quotations list.' },
      { key: 'quotes.create', label: 'Create Quote', description: 'Create new quotations.' },
    ],
  },
  {
    pagePath: '/quotes/search',
    pageTitle: 'Search Inventory',
    category: 'Procurement',
    description: 'Search inventory items and review their source chain.',
    functions: [
      { key: 'quotes.search', label: 'Search Inventory', description: 'Search inventory trace records.' },
    ],
  },
  {
    pagePath: '/challans',
    pageTitle: 'Delivery Challans',
    category: 'Delivery & Inspection',
    description: 'Manage delivery challans and incoming records.',
    functions: [
      { key: 'challans.view', label: 'View Challans', description: 'View challan list and details.' },
      { key: 'challans.create', label: 'Create Challan', description: 'Create delivery challans.' },
      { key: 'challans.edit', label: 'Edit Challan', description: 'Update challan details.' },
      { key: 'challans.verify', label: 'Verify Challan', description: 'Verify received challans.' },
    ],
  },
  {
    pagePath: '/mir',
    pageTitle: 'MIR',
    category: 'Delivery & Inspection',
    description: 'Create and manage material inspection request records.',
    functions: [
      { key: 'mir.view', label: 'View MIR', description: 'Open MIR list and view MIR records.' },
      { key: 'mir.create', label: 'Create MIR', description: 'Create new MIR entries.' },
      { key: 'mir.edit', label: 'Edit MIR', description: 'Edit existing MIR records.' },
      { key: 'mir.delete', label: 'Delete MIR', description: 'Delete MIR records.' },
    ],
  },
  {
    pagePath: '/itr',
    pageTitle: 'ITR',
    category: 'Delivery & Inspection',
    description: 'Create, review, and manage installation test reports.',
    functions: [
      { key: 'itr.view', label: 'View ITR', description: 'Open ITR page and view existing reports.' },
      { key: 'itr.create', label: 'Create ITR', description: 'Create or submit a new installation test report.' },
      { key: 'itr.edit', label: 'Edit ITR', description: 'Edit an existing installation test report.' },
      { key: 'itr.delete', label: 'Delete ITR', description: 'Delete an installation test report.' },
    ],
  },
  {
    pagePath: '/invoices',
    pageTitle: 'Invoices',
    category: 'Delivery & Inspection',
    description: 'Create and manage project invoices.',
    functions: [
      { key: 'invoices.view', label: 'View Invoices', description: 'Open invoices page and view existing invoices.' },
      { key: 'invoices.create', label: 'Create Invoice', description: 'Create a new invoice entry.' },
      { key: 'invoices.edit', label: 'Edit Invoice', description: 'Edit an existing invoice.' },
      { key: 'invoices.delete', label: 'Delete Invoice', description: 'Delete an invoice entry.' },
    ],
  },
  {
    pagePath: '/attendance',
    pageTitle: 'Attendance',
    category: 'Delivery & Inspection',
    description: 'Review attendance submissions with photos and location.',
    functions: [
      { key: 'attendance.view', label: 'View Attendance', description: 'Open attendance list and review records.' },
      { key: 'attendance.preview', label: 'Preview Attendance', description: 'Preview attendance photos and details.' },
    ],
  },
  {
    pagePath: '/mer',
    pageTitle: 'MER',
    category: 'Delivery & Inspection',
    description: 'Manage material entry records and review captured entries.',
    functions: [
      { key: 'mer.view', label: 'View MER', description: 'Open MER page and review records.' },
      { key: 'mer.create', label: 'Create MER', description: 'Create new MER records.' },
      { key: 'mer.edit', label: 'Edit MER', description: 'Edit existing MER records.' },
      { key: 'mer.delete', label: 'Delete MER', description: 'Delete MER records.' },
    ],
  },
  {
    pagePath: '/billing',
    pageTitle: 'Billing & Invoices',
    category: 'Billing',
    description: 'Manage billing records, invoice tracking, and related workflows.',
    functions: [
      { key: 'billing.view', label: 'View Billing', description: 'Open billing page and view invoice data.' },
      { key: 'billing.create', label: 'Create Invoice', description: 'Create new invoices and billing records.' },
      { key: 'billing.edit', label: 'Edit Billing', description: 'Edit billing or invoice details.' },
      { key: 'billing.delete', label: 'Delete Billing Record', description: 'Delete billing or invoice records.' },
    ],
  },
  {
    pagePath: '/inventory',
    pageTitle: 'Inventory',
    category: 'Inventory',
    description: 'Access project inventory module and stock summaries.',
    functions: [
      { key: 'inventory.view', label: 'View Inventory', description: 'Open inventory dashboard and stock information.' },
      { key: 'inventory.add', label: 'Add Inventory', description: 'Add new inventory entries.' },
      { key: 'inventory.edit', label: 'Edit Inventory', description: 'Update existing inventory records.' },
      { key: 'inventory.delete', label: 'Delete Inventory', description: 'Delete inventory records.' },
    ],
  },
  {
    pagePath: '/inventory/add',
    pageTitle: 'Add Inventory',
    category: 'Inventory',
    description: 'Create and manage project inventory entries.',
    functions: [
      { key: 'inventory.add', label: 'Add Inventory', description: 'Add new inventory entries.' },
      { key: 'inventory.edit', label: 'Edit Inventory', description: 'Update existing inventory records.' },
      { key: 'inventory.delete', label: 'Delete Inventory', description: 'Delete inventory records.' },
    ],
  },
  {
    pagePath: '/stock-areas',
    pageTitle: 'Stock Overview',
    category: 'Inventory',
    description: 'Review stock by area and monitor stock distribution.',
    functions: [
      { key: 'stock_areas.view', label: 'View Stock Areas', description: 'Open stock overview by area.' },
      { key: 'stock_areas.create', label: 'Create Stock Area', description: 'Create new stock area records.' },
      { key: 'stock_areas.edit', label: 'Edit Stock Area', description: 'Edit stock area details.' },
      { key: 'stock_areas.delete', label: 'Delete Stock Area', description: 'Delete stock area records.' },
    ],
  },
  {
    pagePath: '/materials',
    pageTitle: 'Product Master',
    category: 'Inventory',
    description: 'Manage product master records and material definitions.',
    functions: [
      { key: 'materials.view', label: 'View Materials', description: 'View product master and materials.' },
      { key: 'materials.create', label: 'Create Material', description: 'Create material or product entries.' },
      { key: 'materials.edit', label: 'Edit Material', description: 'Edit material or product details.' },
      { key: 'materials.delete', label: 'Delete Material', description: 'Delete material or product entries.' },
    ],
  },
  {
    pagePath: '/stock-transfers',
    pageTitle: 'Stock Transfers',
    category: 'Inventory',
    description: 'Track inter-location stock movement and transfer history.',
    functions: [
      { key: 'stock_transfers.view', label: 'View Transfers', description: 'Open stock transfer list and details.' },
      { key: 'stock_transfers.create', label: 'Create Transfer', description: 'Create a stock transfer entry.' },
      { key: 'stock_transfers.edit', label: 'Edit Transfer', description: 'Edit an existing stock transfer.' },
      { key: 'stock_transfers.cancel', label: 'Cancel Transfer', description: 'Cancel or void stock transfer records.' },
    ],
  },
  {
    pagePath: '/consumption',
    pageTitle: 'Consumption',
    category: 'Inventory',
    description: 'Track material consumption and usage records.',
    functions: [
      { key: 'consumption.view', label: 'View Consumption', description: 'Open and review consumption records.' },
      { key: 'consumption.create', label: 'Create Consumption Entry', description: 'Create new consumption entries.' },
      { key: 'consumption.edit', label: 'Edit Consumption Entry', description: 'Update consumption records.' },
      { key: 'consumption.delete', label: 'Delete Consumption Entry', description: 'Delete consumption records.' },
    ],
  },
  {
    pagePath: '/returns',
    pageTitle: 'Returns',
    category: 'Inventory',
    description: 'Manage returned material records and return lifecycle.',
    functions: [
      { key: 'returns.view', label: 'View Returns', description: 'Open returns page and view records.' },
      { key: 'returns.create', label: 'Create Return', description: 'Create a new return entry.' },
      { key: 'returns.edit', label: 'Edit Return', description: 'Edit return records.' },
      { key: 'returns.delete', label: 'Delete Return', description: 'Delete return records.' },
    ],
  },
  {
    pagePath: '/documents',
    pageTitle: 'Repository',
    category: 'Documents',
    description: 'Access project document repository and document actions.',
    functions: [
      { key: 'documents.view', label: 'View Documents', description: 'Open repository and view documents.' },
      { key: 'documents.upload', label: 'Upload Document', description: 'Upload documents to repository.' },
      { key: 'documents.edit', label: 'Edit Document', description: 'Edit document metadata or properties.' },
      { key: 'documents.delete', label: 'Delete Document', description: 'Delete documents from repository.' },
    ],
  },
  {
    pagePath: '/reports',
    pageTitle: 'Reports',
    category: 'Analytics',
    description: 'Review project and operational reports.',
    functions: [
      { key: 'reports.view', label: 'View Reports', description: 'Open reports dashboard and read reports.' },
      { key: 'reports.generate', label: 'Generate Reports', description: 'Generate reports from current data.' },
      { key: 'reports.export', label: 'Export Reports', description: 'Export reports for external use.' },
    ],
  },
  {
    pagePath: '/audit-logs',
    pageTitle: 'Audit Logs',
    category: 'Analytics',
    description: 'Review audit trails and system activity logs.',
    functions: [
      { key: 'audit_logs.view', label: 'View Audit Logs', description: 'Open and read audit logs.' },
      { key: 'audit_logs.filter', label: 'Filter Audit Logs', description: 'Filter audit logs by user, date, or action.' },
      { key: 'audit_logs.export', label: 'Export Audit Logs', description: 'Export audit logs for compliance checks.' },
    ],
  },
  {
    pagePath: '/settings',
    pageTitle: 'Profile Settings',
    category: 'Administration',
    description: 'Manage your profile and application preferences.',
    functions: [],
  },
  {
    pagePath: '/user-management',
    pageTitle: 'User Management',
    category: 'Administration',
    description: 'Manage users, roles, and project assignments.',
    functions: [
      { key: 'settings.user_management', label: 'Manage Users', description: 'View and manage users.' },
    ],
  },
  {
    pagePath: '/access-control',
    pageTitle: 'Access Control',
    category: 'Administration',
    description: 'Configure page and function visibility per user.',
    functions: [
      { key: 'settings.access_control', label: 'Manage Access Control', description: 'View and manage access control settings.' },
    ],
  },
];

export const ACCESS_CONTROL_PAGE_PATHS = ACCESS_CONTROL_CATALOG.map((page) => page.pagePath);

export const ACCESS_CONTROL_FUNCTION_KEYS = ACCESS_CONTROL_CATALOG.flatMap((page) =>
  page.functions.map((fn) => fn.key)
);
