import 'dart:io';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:path_provider/path_provider.dart';
import 'file_service.dart';

/// PDF generation and printing service
class PdfService {
  /// Generate a PDF document
  static Future<pw.Document> createDocument({
    PdfPageFormat pageFormat = PdfPageFormat.a4,
  }) async {
    return pw.Document(
      creator: 'Madhuram App',
      producer: 'Madhuram Construction Management',
    );
  }

  /// Build a standard header for reports
  static pw.Widget buildHeader({
    required String title,
    String? subtitle,
    String? projectName,
    String? date,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(bottom: 16),
      decoration: const pw.BoxDecoration(
        border: pw.Border(bottom: pw.BorderSide(width: 1, color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(title, style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold)),
              if (subtitle != null) pw.SizedBox(height: 4),
              if (subtitle != null) pw.Text(subtitle, style: const pw.TextStyle(fontSize: 12, color: PdfColors.grey700)),
              if (projectName != null) pw.SizedBox(height: 8),
              if (projectName != null) pw.Text('Project: $projectName', style: const pw.TextStyle(fontSize: 10)),
            ],
          ),
          if (date != null)
            pw.Text(date, style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
        ],
      ),
    );
  }

  /// Build a standard footer
  static pw.Widget buildFooter(pw.Context context) {
    return pw.Container(
      padding: const pw.EdgeInsets.only(top: 8),
      decoration: const pw.BoxDecoration(
        border: pw.Border(top: pw.BorderSide(width: 0.5, color: PdfColors.grey300)),
      ),
      child: pw.Row(
        mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
        children: [
          pw.Text('Generated by Madhuram', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
          pw.Text('Page ${context.pageNumber} of ${context.pagesCount}', style: const pw.TextStyle(fontSize: 8, color: PdfColors.grey500)),
        ],
      ),
    );
  }

  /// Build a table
  static pw.Widget buildTable({
    required List<String> headers,
    required List<List<String>> rows,
    List<int>? columnWidths,
  }) {
    return pw.TableHelper.fromTextArray(
      headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10),
      cellStyle: const pw.TextStyle(fontSize: 9),
      headerDecoration: const pw.BoxDecoration(color: PdfColors.grey200),
      cellHeight: 28,
      cellAlignments: Map.fromIterables(
        List.generate(headers.length, (i) => i),
        List.generate(headers.length, (i) => pw.Alignment.centerLeft),
      ),
      headers: headers,
      data: rows,
    );
  }

  /// Build a summary box
  static pw.Widget buildSummaryBox({
    required String title,
    required Map<String, String> items,
  }) {
    return pw.Container(
      padding: const pw.EdgeInsets.all(12),
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey300),
        borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
      ),
      child: pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(title, style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          ...items.entries.map((e) => pw.Padding(
            padding: const pw.EdgeInsets.symmetric(vertical: 2),
            child: pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                pw.Text(e.key, style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey700)),
                pw.Text(e.value, style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold)),
              ],
            ),
          )),
        ],
      ),
    );
  }

  static String _stringValue(dynamic value, [String fallback = '']) {
    final text = value?.toString().trim() ?? '';
    return text.isEmpty || text.toLowerCase() == 'null' ? fallback : text;
  }

  static double _doubleValue(dynamic value) {
    if (value == null) return 0;
    if (value is num) return value.toDouble();
    final normalized = value.toString().replaceAll(',', '').trim();
    return double.tryParse(normalized) ?? 0;
  }

  static List<String> _stringList(dynamic value) {
    if (value is List) {
      return value
          .map((e) => e.toString().trim())
          .where((e) => e.isNotEmpty)
          .toList();
    }
    if (value is String && value.trim().isNotEmpty) {
      return value
          .split('\n')
          .map((e) => e.trim())
          .where((e) => e.isNotEmpty)
          .toList();
    }
    return const [];
  }

  static List<Map<String, dynamic>> _normalizePoItems(dynamic rawItems) {
    if (rawItems is! List) return const [];
    return rawItems
        .whereType<Map>()
        .map((item) => Map<String, dynamic>.from(item))
        .map((item) {
          final qty = _doubleValue(
            item['qty'] ?? item['quantity'] ?? item['Qty'],
          );
          final rate = _doubleValue(item['Rate'] ?? item['rate'] ?? item['price']);
          final amount = _doubleValue(item['Amount'] ?? item['amount']) != 0
              ? _doubleValue(item['Amount'] ?? item['amount'])
              : qty * rate;
          return <String, dynamic>{
            'srNo': _stringValue(item['srNo'] ?? item['srno']),
            'hsnCode': _stringValue(item['hsnCode'] ?? item['hsn']),
            'description': _stringValue(item['description']),
            'qty': qty,
            'uom': _stringValue(item['uom'] ?? item['UOM']),
            'rate': rate,
            'amount': amount,
            'remarks': _stringValue(item['remarks'] ?? item['remark']),
          };
        })
        .toList();
  }

  /// Save PDF to file
  static Future<File?> saveToFile(pw.Document doc, String filename) async {
    try {
      final bytes = await doc.save();
      return await FileService.saveFile(filename: filename, bytes: bytes, subfolder: 'reports');
    } catch (e) {
      print('Error saving PDF: $e');
    }
    return null;
  }

  /// Share PDF
  static Future<void> sharePdf(pw.Document doc, String filename) async {
    try {
      final bytes = await doc.save();
      final dir = await getTemporaryDirectory();
      final file = File('${dir.path}/$filename');
      await file.writeAsBytes(bytes);
      await FileService.shareFile(file, subject: filename);
    } catch (e) {
      print('Error sharing PDF: $e');
    }
  }

  /// Print PDF
  static Future<bool> printPdf(pw.Document doc) async {
    try {
      return await Printing.layoutPdf(
        onLayout: (format) async => doc.save(),
        name: 'Madhuram Report',
      );
    } catch (e) {
      print('Error printing PDF: $e');
    }
    return false;
  }

  /// Preview PDF
  static Future<void> previewPdf(pw.Document doc) async {
    await Printing.layoutPdf(
      onLayout: (format) async => doc.save(),
    );
  }

  /// Generate BOQ Report
  static Future<pw.Document> generateBOQReport({
    required String projectName,
    required List<Map<String, dynamic>> items,
  }) async {
    final doc = await createDocument();
    final now = DateTime.now();
    final dateStr = '${now.day}/${now.month}/${now.year}';

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => buildHeader(
          title: 'Bill of Quantities',
          subtitle: 'Project Material List',
          projectName: projectName,
          date: dateStr,
        ),
        footer: buildFooter,
        build: (context) => [
          pw.SizedBox(height: 20),
          buildTable(
            headers: ['S.No', 'Item Description', 'Unit', 'Quantity', 'Rate', 'Amount'],
            rows: items.asMap().entries.map((e) => [
              (e.key + 1).toString(),
              (e.value['description'] ?? '').toString(),
              (e.value['unit'] ?? '').toString(),
              (e.value['quantity'] ?? 0).toString(),
              '₹${e.value['rate'] ?? 0}',
              '₹${e.value['amount'] ?? 0}',
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              buildSummaryBox(
                title: 'Summary',
                items: {
                  'Total Items': items.length.toString(),
                  'Total Amount': '₹${items.fold<num>(0, (sum, item) => sum + (item['amount'] ?? 0)).toStringAsFixed(2)}',
                },
              ),
            ],
          ),
        ],
      ),
    );

    return doc;
  }

  /// Generate Purchase Order PDF
  static Future<pw.Document> generatePurchaseOrderPdf(
    Map<String, dynamic> poData, {
    String? projectName,
  }) async {
    final doc = await createDocument();
    final raw = Map<String, dynamic>.from(poData);
    final vendor = raw['vendor'] is Map
        ? Map<String, dynamic>.from(raw['vendor'] as Map)
        : <String, dynamic>{};
    final contacts = vendor['contacts'] is Map
        ? Map<String, dynamic>.from(vendor['contacts'] as Map)
        : <String, dynamic>{};
    final primary = contacts['primary'] is Map
        ? Map<String, dynamic>.from(contacts['primary'] as Map)
        : <String, dynamic>{};
    final secondary = contacts['secondary'] is Map
        ? Map<String, dynamic>.from(contacts['secondary'] as Map)
        : <String, dynamic>{};
    final discount = raw['discount'] is Map
        ? Map<String, dynamic>.from(raw['discount'] as Map)
        : <String, dynamic>{};
    final taxes = raw['taxes'] is Map
        ? Map<String, dynamic>.from(raw['taxes'] as Map)
        : <String, dynamic>{};
    final cgst = taxes['cgst'] is Map
        ? Map<String, dynamic>.from(taxes['cgst'] as Map)
        : <String, dynamic>{};
    final sgst = taxes['sgst'] is Map
        ? Map<String, dynamic>.from(taxes['sgst'] as Map)
        : <String, dynamic>{};
    final summary = raw['summary'] is Map
        ? Map<String, dynamic>.from(raw['summary'] as Map)
        : <String, dynamic>{};
    final items = _normalizePoItems(raw['items']);
    final poNumber = _stringValue(raw['order_no'] ?? raw['orderNo'] ?? raw['poNumber']);
    final poDate = _stringValue(raw['po_date'] ?? raw['poDate']);
    final dateStr = poDate.isNotEmpty ? poDate : '${DateTime.now().day}/${DateTime.now().month}/${DateTime.now().year}';
    final resolvedProjectName = projectName ??
        _stringValue(raw['project_name'] ?? raw['projectName'] ?? raw['project_id'], 'Purchase Order');
    final totalAmount = _doubleValue(raw['total_amount'] ?? raw['totalAmount']);
    final afterDiscount = _doubleValue(raw['afterDiscountAmount'] ?? raw['after_discount']);
    final notes = _stringList(raw['notes']);
    final terms = _stringList(raw['termsAndConditions']);
    final subtotal = items.fold<double>(0, (sum, item) => sum + (item['amount'] as double? ?? 0));
    final companyName = _stringValue(raw['companyName'] ?? raw['company_name']);
    final companySubtitle = _stringValue(raw['companySubtitle'] ?? raw['company_subtitle']);
    final companyEmail = _stringValue(raw['companyEmail'] ?? raw['company_email']);
    final companyGst = _stringValue(raw['companyGstNo'] ?? raw['company_gst']);
    final indentNo = _stringValue(raw['indentNo'] ?? raw['indent_no']);
    final indentDate = _stringValue(raw['indentDate'] ?? raw['indent_date']);
    final status = _stringValue(raw['status'], 'created');
    final vendorName = _stringValue(vendor['name'] ?? raw['vendor_name']);
    final vendorSite = _stringValue(vendor['site'] ?? raw['site']);
    final vendorAddress = _stringValue(vendor['address'] ?? raw['vendor_address']);
    final contactPerson = _stringValue(vendor['contactPerson'] ?? raw['contact_person']);
    final primaryName = _stringValue(primary['name'] ?? raw['primary_contact_name']);
    final primaryPhone = _stringValue(primary['phone'] ?? primary['number'] ?? raw['primary_contact_number']);
    final secondaryName = _stringValue(secondary['name'] ?? raw['secondary_contact_name']);
    final secondaryPhone = _stringValue(secondary['phone'] ?? secondary['number'] ?? raw['secondary_contact_number']);

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => buildHeader(
          title: 'Purchase Order',
          subtitle: poNumber.isEmpty ? 'Draft PO' : poNumber,
          projectName: resolvedProjectName,
          date: dateStr,
        ),
        footer: buildFooter,
        build: (context) => [
          pw.SizedBox(height: 16),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Header Details', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                      pw.SizedBox(height: 6),
                      pw.Text('PO No: ${poNumber.isEmpty ? '-' : poNumber}', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('PO Date: ${poDate.isEmpty ? '-' : poDate}', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('Indent No: ${indentNo.isEmpty ? '-' : indentNo}', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('Indent Date: ${indentDate.isEmpty ? '-' : indentDate}', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('Status: ${status.isEmpty ? 'created' : status}', style: const pw.TextStyle(fontSize: 9)),
                    ],
                  ),
                ),
              ),
              pw.SizedBox(width: 12),
              pw.Expanded(
                child: pw.Container(
                  padding: const pw.EdgeInsets.all(10),
                  decoration: pw.BoxDecoration(
                    border: pw.Border.all(color: PdfColors.grey300),
                    borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                  ),
                  child: pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text('Vendor Details', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                      pw.SizedBox(height: 6),
                      pw.Text(vendorName.isEmpty ? '-' : vendorName, style: const pw.TextStyle(fontSize: 9)),
                      pw.Text(vendorSite.isEmpty ? '-' : vendorSite, style: const pw.TextStyle(fontSize: 9)),
                      pw.Text(contactPerson.isEmpty ? '-' : contactPerson, style: const pw.TextStyle(fontSize: 9)),
                      pw.Text(vendorAddress.isEmpty ? '-' : vendorAddress, style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('Primary: ${primaryName.isEmpty ? '-' : primaryName} / ${primaryPhone.isEmpty ? '-' : primaryPhone}', style: const pw.TextStyle(fontSize: 9)),
                      pw.Text('Secondary: ${secondaryName.isEmpty ? '-' : secondaryName} / ${secondaryPhone.isEmpty ? '-' : secondaryPhone}', style: const pw.TextStyle(fontSize: 9)),
                    ],
                  ),
                ),
              ),
            ],
          ),
          if (companyName.isNotEmpty || companySubtitle.isNotEmpty || companyEmail.isNotEmpty || companyGst.isNotEmpty) ...[
            pw.SizedBox(height: 10),
            pw.Container(
              width: double.infinity,
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                color: PdfColors.grey50,
                border: pw.Border.all(color: PdfColors.grey300),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
              ),
              child: pw.Text(
                [
                  if (companyName.isNotEmpty) companyName,
                  if (companySubtitle.isNotEmpty) companySubtitle,
                  if (companyEmail.isNotEmpty) companyEmail,
                  if (companyGst.isNotEmpty) 'GST: $companyGst',
                ].join('  |  '),
                style: const pw.TextStyle(fontSize: 9),
              ),
            ),
          ],
          pw.SizedBox(height: 20),
          buildTable(
            headers: ['S.No', 'HSN', 'Description', 'Qty', 'UOM', 'Rate', 'Amount', 'Remarks'],
            rows: items.asMap().entries.map((e) => [
              _stringValue(e.value['srNo'], (e.key + 1).toString()),
              _stringValue(e.value['hsnCode']),
              _stringValue(e.value['description']),
              _stringValue(e.value['qty']),
              _stringValue(e.value['uom']),
              '₹${(_doubleValue(e.value['rate'])).toStringAsFixed(2)}',
              '₹${(_doubleValue(e.value['amount'])).toStringAsFixed(2)}',
              _stringValue(e.value['remarks']),
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Expanded(
                child: buildSummaryBox(
                  title: 'Amounts & Delivery',
                  items: {
                    'Subtotal': '₹${subtotal.toStringAsFixed(2)}',
                    'Discount %': _stringValue(discount['percent']),
                    'Discount Amount': '₹${_doubleValue(discount['amount']).toStringAsFixed(2)}',
                    'After Discount': '₹${afterDiscount.toStringAsFixed(2)}',
                    'CGST %': _stringValue(cgst['percent']),
                    'CGST Amount': '₹${_doubleValue(cgst['amount']).toStringAsFixed(2)}',
                    'SGST %': _stringValue(sgst['percent']),
                    'SGST Amount': '₹${_doubleValue(sgst['amount']).toStringAsFixed(2)}',
                    'Total Amount': '₹${totalAmount.toStringAsFixed(2)}',
                    'Delivery': _stringValue(summary['delivery']),
                    'Payment': _stringValue(summary['payment']),
                  },
                ),
              ),
              if (notes.isNotEmpty || terms.isNotEmpty) ...[
                pw.SizedBox(width: 12),
                pw.Expanded(
                  child: pw.Column(
                    children: [
                      if (notes.isNotEmpty)
                        pw.Container(
                          width: double.infinity,
                          padding: const pw.EdgeInsets.all(10),
                          decoration: pw.BoxDecoration(
                            border: pw.Border.all(color: PdfColors.grey300),
                            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                          ),
                          child: pw.Column(
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text('Notes', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                              pw.SizedBox(height: 6),
                              ...notes.map((line) => pw.Padding(
                                padding: const pw.EdgeInsets.only(bottom: 3),
                                child: pw.Text('• $line', style: const pw.TextStyle(fontSize: 9)),
                              )),
                            ],
                          ),
                        ),
                      if (notes.isNotEmpty && terms.isNotEmpty) pw.SizedBox(height: 10),
                      if (terms.isNotEmpty)
                        pw.Container(
                          width: double.infinity,
                          padding: const pw.EdgeInsets.all(10),
                          decoration: pw.BoxDecoration(
                            border: pw.Border.all(color: PdfColors.grey300),
                            borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
                          ),
                          child: pw.Column(
                            crossAxisAlignment: pw.CrossAxisAlignment.start,
                            children: [
                              pw.Text('Terms & Conditions', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
                              pw.SizedBox(height: 6),
                              ...terms.map((line) => pw.Padding(
                                padding: const pw.EdgeInsets.only(bottom: 3),
                                child: pw.Text('• $line', style: const pw.TextStyle(fontSize: 9)),
                              )),
                            ],
                          ),
                        ),
                    ],
                  ),
                ),
              ],
            ],
          ),
          pw.SizedBox(height: 50),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
            children: [
              pw.Column(
                children: [
                  pw.Container(width: 150, height: 1, color: PdfColors.black),
                  pw.SizedBox(height: 4),
                  pw.Text('Authorized Signature', style: const pw.TextStyle(fontSize: 9)),
                ],
              ),
              pw.Column(
                children: [
                  pw.Container(width: 150, height: 1, color: PdfColors.black),
                  pw.SizedBox(height: 4),
                  pw.Text('Vendor Acceptance', style: const pw.TextStyle(fontSize: 9)),
                ],
              ),
            ],
          ),
        ],
      ),
    );

    return doc;
  }

  static Future<String?> exportPurchaseOrderPdf(
    pw.Document doc,
    String filename,
  ) async {
    try {
      final bytes = await doc.save();
      return await FileService.saveFileAs(
        filename: filename.endsWith('.pdf') ? filename : '$filename.pdf',
        bytes: bytes,
      );
    } catch (e) {
      print('Error exporting PDF: $e');
    }
    return null;
  }

  /// Generate Purchase Request (Material Request) PDF
  static Future<pw.Document> generatePurchaseRequestPdf({
    required String prNumber,
    required String projectName,
    required String workOrder,
    required String location,
    required String mirNo,
    required String urgency,
    required String date,
    required String approvedBy,
    required List<Map<String, dynamic>> items,
  }) async {
    final doc = await createDocument();

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(24),
        build: (context) {
          return [
            pw.Container(
              padding: const pw.EdgeInsets.only(bottom: 12),
              decoration: const pw.BoxDecoration(
                border: pw.Border(
                  bottom: pw.BorderSide(width: 0.5, color: PdfColors.grey400),
                ),
              ),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  pw.Column(
                    crossAxisAlignment: pw.CrossAxisAlignment.start,
                    children: [
                      pw.Text(
                        'Material Request',
                        style: pw.TextStyle(
                          fontSize: 18,
                          fontWeight: pw.FontWeight.bold,
                        ),
                      ),
                      pw.SizedBox(height: 4),
                      pw.Text(
                        prNumber,
                        style: const pw.TextStyle(
                          fontSize: 10,
                          color: PdfColors.grey700,
                        ),
                      ),
                    ],
                  ),
                  pw.Text(
                    date,
                    style: const pw.TextStyle(
                      fontSize: 10,
                      color: PdfColors.grey700,
                    ),
                  ),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            pw.Container(
              padding: const pw.EdgeInsets.all(10),
              decoration: pw.BoxDecoration(
                border: pw.Border.all(color: PdfColors.grey400),
                borderRadius: const pw.BorderRadius.all(pw.Radius.circular(4)),
              ),
              child: pw.Column(
                crossAxisAlignment: pw.CrossAxisAlignment.start,
                children: [
                  _buildInfoRow('Project Name', projectName),
                  _buildInfoRow('Work Order', workOrder),
                  _buildInfoRow('Location', location),
                  _buildInfoRow('MIR No', mirNo),
                  _buildInfoRow('Urgency', urgency),
                  _buildInfoRow('Approved By', approvedBy),
                ],
              ),
            ),
            pw.SizedBox(height: 16),
            buildTable(
              headers: const [
                'Sr.',
                'Material Description',
                'Unit',
                'Req. Qty',
                'Make',
                'Place of Utilisation',
              ],
              rows: items.asMap().entries.map((entry) {
                final index = entry.key + 1;
                final item = entry.value;
                return [
                  index.toString(),
                  (item['material_description'] ?? '').toString(),
                  (item['unit'] ?? '').toString(),
                  (item['req_qty'] ?? '').toString(),
                  (item['make'] ?? '').toString(),
                  (item['place_of_utilisation'] ?? '').toString(),
                ];
              }).toList(),
            ),
            pw.SizedBox(height: 24),
            pw.Row(
              mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
              children: [
                _buildSignatureBox('Requested By'),
                _buildSignatureBox('Checked By'),
                _buildSignatureBox('Approved By'),
              ],
            ),
          ];
        },
      ),
    );

    return doc;
  }

  static pw.Widget _buildInfoRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 90,
            child: pw.Text(
              '$label:',
              style: pw.TextStyle(fontSize: 9, fontWeight: pw.FontWeight.bold),
            ),
          ),
          pw.Expanded(
            child: pw.Text(
              value.isEmpty ? '-' : value,
              style: const pw.TextStyle(fontSize: 9),
            ),
          ),
        ],
      ),
    );
  }

  static pw.Widget _buildSignatureBox(String label) {
    return pw.Container(
      width: 160,
      height: 40,
      decoration: pw.BoxDecoration(
        border: pw.Border.all(color: PdfColors.grey400),
      ),
      alignment: pw.Alignment.bottomCenter,
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Text(
        label,
        style: const pw.TextStyle(fontSize: 9),
      ),
    );
  }

  /// Generate Invoice PDF
  static Future<pw.Document> generateInvoicePdf({
    required String invoiceNumber,
    required String clientName,
    required String projectName,
    required List<Map<String, dynamic>> items,
    required double totalAmount,
    double taxRate = 18.0,
  }) async {
    final doc = await createDocument();
    final now = DateTime.now();
    final dateStr = '${now.day}/${now.month}/${now.year}';
    final taxAmount = totalAmount * (taxRate / 100);
    final grandTotal = totalAmount + taxAmount;

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        header: (context) => buildHeader(
          title: 'Invoice',
          subtitle: invoiceNumber,
          projectName: projectName,
          date: dateStr,
        ),
        footer: buildFooter,
        build: (context) => [
          pw.SizedBox(height: 16),
          pw.Text('Bill To: $clientName', style: pw.TextStyle(fontWeight: pw.FontWeight.bold, fontSize: 10)),
          pw.SizedBox(height: 20),
          buildTable(
            headers: ['S.No', 'Description', 'Quantity', 'Rate', 'Amount'],
            rows: items.asMap().entries.map((e) => [
              (e.key + 1).toString(),
              (e.value['description'] ?? '').toString(),
              (e.value['quantity'] ?? 0).toString(),
              '₹${e.value['rate'] ?? 0}',
              '₹${((e.value['quantity'] ?? 0) * (e.value['rate'] ?? 0)).toStringAsFixed(2)}',
            ]).toList(),
          ),
          pw.SizedBox(height: 20),
          pw.Row(
            mainAxisAlignment: pw.MainAxisAlignment.end,
            children: [
              pw.Container(
                width: 200,
                child: pw.Column(
                  children: [
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Subtotal:', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('₹${totalAmount.toStringAsFixed(2)}', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('GST ($taxRate%):', style: const pw.TextStyle(fontSize: 10)),
                        pw.Text('₹${taxAmount.toStringAsFixed(2)}', style: const pw.TextStyle(fontSize: 10)),
                      ],
                    ),
                    pw.SizedBox(height: 4),
                    pw.Divider(),
                    pw.SizedBox(height: 4),
                    pw.Row(
                      mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                      children: [
                        pw.Text('Grand Total:', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                        pw.Text('₹${grandTotal.toStringAsFixed(2)}', style: pw.TextStyle(fontSize: 12, fontWeight: pw.FontWeight.bold)),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ],
      ),
    );

    return doc;
  }
}
